from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator

def validate_phone(value):
    return True

def validate_username(value):
    return True